### PR TITLE
Upgrade to JHipster 8.4

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mshima** [comment]
Spring Boot 3.2.3 requires hibernate to be downgraded for native support:
https://github.com/spring-projects/spring-boot/releases/tag/v3.2.3

We probably need to wait for JHipster 3.2.4.

**Comment by mraible** [comment]
You are correct. If I try to generate an app locally (with `jhipster-native --defaults`) and build a native image, it says `hibernate.version` is not defined.

```
$ npm run native-package

> native@0.0.1-SNAPSHOT native-package
> ./mvnw package -B -ntp -Pnative,prod -DskipTests

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'build.plugins.plugin.version' for org.hibernate.orm.tooling:hibernate-enhance-maven-plugin must be a valid version but is '${hibernate.version}'. @ line 1116, column 34
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.mycompany.myapp:native:0.0.1-SNAPSHOT (/Users/mraible/Downloads/native/pom.xml) has 1 error
[ERROR]     'build.plugins.plugin.version' for org.hibernate.orm.tooling:hibernate-enhance-maven-plugin must be a valid version but is '${hibernate.version}'. @ line 1116, column 34
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

If I add `<hibernate.version>6.4.2.Final</hibernate.version>`, it still fails because this is not the version that's used. 

```
$ mvn dependency:tree | grep hibernate
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-hibernate6:jar:2.15.4:compile
[INFO] +- org.hibernate.orm:hibernate-core:jar:6.4.4.Final:compile
[INFO] |  +- org.hibernate.common:hibernate-commons-annotations:jar:6.0.6.Final:runtime
[INFO] +- org.hibernate.orm:hibernate-jcache:jar:6.4.4.Final:compile
[INFO] +- org.hibernate.orm:hibernate-jpamodelgen:jar:6.4.4.Final:provided
[INFO] +- org.hibernate.validator:hibernate-validator:jar:8.0.1.Final:compile
```

**Comment by mshima** [comment]
> If I add `<hibernate.version>6.4.2.Final</hibernate.version>`, it still fails because this is not the version that's used.

This should work in jhipster main due to spring boot parent, won’t work in v 8.2.1.

**Comment by mraible** [comment]
Should the title of this PR be 8.3 now?

**Comment by mshima** [comment]
Maven is not running with correct profile.
```
[0] :: JHipster 🤓  :: Running Spring Boot 3.2.4 :: Startup profile(s)  ::
[0] :: https://www.jhipster.tech/ ::
[0] 
[0] 2024-04-16T22:44:30.954Z  INFO 5215 --- [           main] com.mycompany.myapp.JhipsterApp          : Starting AOT-processed JhipsterApp using Java 17.0.9 with PID 5215 (/home/runner/work/generator-jhipster-native/generator-jhipster-native/app/target/native-executable started by runner in /home/runner/work/generator-jhipster-native/generator-jhipster-native/app) 
[0] 2024-04-16T22:44:30.954Z DEBUG 5215 --- [           main] com.mycompany.myapp.JhipsterApp          : Running with Spring Boot v3.2.4, Spring v6.1.5 
[0] 2024-04-16T22:44:30.954Z  INFO 5215 --- [           main] com.mycompany.myapp.JhipsterApp          : No active profile set, falling back to 2 default profiles: "dev", "api-docs"
```

**Comment by mraible** [comment]
Maybe this is fixed by https://github.com/jhipster/generator-jhipster/pull/25980 in JHipster 8.4.0?

**Comment by mshima** [comment]
It's missing gradle + webflux now.

**Pull request merged**
