### PR TITLE
Added missing AddColumnConfig

### PR DESCRIPTION
**Pull request by akang**

### CODE REVIEW

**Comment by mshima** [comment]
Would be nice to have some reference to this error. But not mandatory.
Looks related to incremental liquibase. Is it?

**Comment by akang** [comment]
Hi @mshima ,

Yes its related to Liquibase. Saw that it was required when running the native binary. Sorry for the lack of comments!

thanks
aka

**Comment by atomfrede** [comment]
Thanks for the contribution. Indeed we didn't check the incremental changelog part.

**Review by atomfrede — APPROVED** [review]

**Comment by mshima** [comment]
Thanks @akang

**Pull request merged**
