### PR TITLE
Change native-executable to be artifactId-version

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mshima** [comment]
It’s fixed due to scripts.
https://github.com/jhipster/generator-jhipster-native/blob/7217fe29ad6a68d50a265f5cbcdf2ddce656be93/generators/server/generator.mjs#L35-L36

We can pass as parameter to native-package script.

**Comment by mraible** [comment]
Is `native-start` used by CI or something? I don't tend to use many of the scripts in `package.json`.

**Comment by mshima** [comment]
> Is `native-start` used by CI or something? I don't tend to use many of the scripts in `package.json`.

Yes

**Comment by mshima** [comment]
We should change 
https://github.com/jhipster/generator-jhipster-native/blob/7217fe29ad6a68d50a265f5cbcdf2ddce656be93/generators/server/generator.mjs#L37

to something like `npm run native-package -- -DnativeImage=native-executable`

**Comment by mraible** [comment]
I think it's OK to leave it. I tend to use Maven and Gradle more than npm when developing a JHispter app.

**Pull request closed without merging**
