### PR TITLE
update generator-jhipster v8.0.0

### PR DESCRIPTION
**Pull request by mshima**

### CODE REVIEW

**Comment by mshima** [comment]
The error is fixed:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'org.springframework.aot.hint.support.FilePatternResourceHintsRegistrar$Builder org.springframework.aot.hint.support.FilePatternResourceHintsRegistrar.forClassPathLocations(java.util.List)'
```

jwt applications are failing now:
```
[0] Caused by: java.lang.ClassCastException: org.springframework.aop.framework.CglibAopProxy$SerializableNoOp cannot be cast to org.springframework.cglib.proxy.Dispatcher
[0] 	at com.mycompany.myapp.service.MailService$$SpringCGLIB$$0.setCallbacks(<generated>)
[0] 	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:91)
[0] 	at org.springframework.aop.framework.CglibAopProxy.buildProxy(CglibAopProxy.java:213)
```

**Comment by mshima** [comment]
Merging since main is not passing anyway.

**Comment by hide212131** [comment]
@mshima Thank you for the swift update to v8. I will also look into the error causes on my end.

**Comment by hide212131** [comment]
> ```
> [0] Caused by: java.lang.ClassCastException: org.springframework.aop.framework.CglibAopProxy$SerializableNoOp cannot be cast to org.springframework.cglib.proxy.Dispatcher
> [0] 	at com.mycompany.myapp.service.MailService$$SpringCGLIB$$0.setCallbacks(<generated>)
> [0] 	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:91)
> [0] 	at org.springframework.aop.framework.CglibAopProxy.buildProxy(CglibAopProxy.java:213)
> ```

@mshima 

I came across a similar issue here:
https://github.com/spring-projects/spring-framework/issues/30985

I attempted to analyze it myself, but it has been challenging and time-consuming to resolve issues such as the unintended creation of two CGLIB classes( MailService$$SpringCGLIB$$0 and MailService$$SpringCGLIB$$1, with the latter being the correct one), where the behavior remains unclear.

I plan to modify the code to avoid using `@Lazy` in `MailService`.

**Pull request merged**
