### PR TITLE
Support for Spring Boot 3

### PR DESCRIPTION
**Pull request by hide212131**
Resolves https://github.com/jhipster/generator-jhipster/issues/22488

This PR aims to enable the upcoming JHipster 8 to build native images using Spring Boot 3 and GraalVM. This is set up as a Draft PR to be developed in phases:

- [X] Firstly, adapt the current code for the new JHipster 8 blueprint specifications
  - Referring to the code generated by v8's `jhipster generate-blueprint`
  - Ensure that the blueprint execution is successful, modify the sample app [Blog App](https://github.com/mraible/blog-oauth2-native) code, and achieve successful build and launch of the (non-native) app. 
- [x] Modify for Spring Boot 3 + GraalVM 
  - Ensure the Blog App code operates in native mode (`npm run e2e` should pass).
- [x] Refactor in line with the latest blueprint specifications 
  - For instance, modularizing with maven or gradle, etc.
- [ ] Enhance to meet the features of jhipster-native@1.3.2
  - [x] Make it build successfully with Gradle
  - Add metadata to ensure e2e passes
    - [x] PostgreSQL
    - [x] Webflux
    - [x] JWT
  - Adjust Tests workflow
    -  ensure CI passes
        - [x] Ubuntu
        - [x] macos
        - [ ]  Windows (https://github.com/jhipster/generator-jhipster-native/pull/85#issuecomment-1713866906)
    - [ ] Add MySQL to JDL tests workflow
    - [ ] Enable cacheProvider, enableHibernateCache (it should work)
  - Check past issues/PRs. 
    - [ ] https://github.com/jhipster/generator-jhipster-native/pull/80
    - [ ] https://github.com/jhipster/generator-jhipster-native/issues/10
    - [ ] https://github.com/jhipster/generator-jhipster-native/issues/15
    - [ ] https://github.com/jhipster/generator-jhipster-native/issues/20
    - [ ] https://github.com/jhipster/generator-jhipster-native/pull/17

Reference: https://github.com/mraible/blog-oauth2-native/pull/1

### CODE REVIEW

**Comment by hide212131** [comment]
@mshima 

I have been working while referencing the https://github.com/jhipster/generator-jhipster/pull/23194 branch. Since it was recently merged into the main branch, I decided to submit this PR. 

I will continue my work, but if there's anything unusual about the current process or the code as it stands, I'd appreciate any comments or feedback.

**Comment by hide212131** [comment]
@mshima I'd like to tap into your wisdom.
I've split the sub generators, but `ci-cd` and `entities` haven't been executed. Everything else has been done correctly.
What setting is missing?

**Comment by hide212131** [comment]
@mshima  My apologies. It seems that both are activated when specifying 'ci-ci' and 'entities' in the command line options. Sorry for the confusion.

**Comment by mraible** [comment]
@hide212131 Let me know if there's anything I can do to help with this. I'm happy to help, even if it's just QAing different combinations.

**Comment by hide212131** [comment]
@mraible Thank you so much! I'm very glad to hear that 😊
I've broken down the tasks for completion in the description.
I plan to tackle Gradle and PostgreSQL this weekend.
Even with the current blueprint, Maven works. If we can divide the tasks starting from Webflux, I believe we'll be able to finish much faster.

**Comment by mshima** [comment]
@hide212131 do you want me to take a look at generation error?

**Comment by hide212131** [comment]
@mshima Thank you so much for your offer. 
Until now, I have been testing with the `jhipster --blueprint native` format, but in the CI, it's producing an error with the `jhipster-native` command format. 
I was actually thinking that getting your insight might be the best way to resolve this issue.

**Comment by hide212131** [comment]
I apologize for the confusion. 
The command format wasn't the issue. Until now, I've been executing the `jhipster --blueprints native` on already generated code. On the CI side, the code is generated while applying the blueprint, which is the difference.

**Comment by hide212131** [comment]
I'll be checking the JWT. 
From now on, I'll indicate items that I'm working on by writing 'Testing' in the description.

**Comment by hide212131** [comment]
@mshima The issue where an error occurs in CI (when generating code while applying the blueprint) has not been resolved yet.
When `POST_WRITING_ENTITIES` is called, the state of the store that Yeoman holds is as follows, which explains why ServerGenerator's `readDestination` can either succeed or fail:
- `web/rest/BlogResource.java`: Success, as it is registered.
- `domain/Blog.java`: Failure, even though it is registered, the key is `Blog.java.jhi`.
- `web/rest/UserResource.java`: Failure, as it is not registered.

**Comment by mshima** [comment]
Posted te `jhi` file issued at https://github.com/jhipster/generator-jhipster/issues/23391.

**Comment by hide212131** [comment]
@mraible @mshima I've updated the blueprint's features for v8, which includes webflux. 
The current status is described at the [beginning](https://github.com/jhipster/generator-jhipster-native/pull/85#issue-1859665897). I'd appreciate any advice on the following issues:

- The `postgresql-webflux` CI doesn't pass. Do you have any suggestions for resolving this? It seems it might take some time to create a minimal reproducible case in Spring Boot 3 (I believe the issue isn't related to JHipster).
  - When adding `org.graalvm.buildtools.native` to plugins in gradle, an error occurs in the `Task: processTestAot`, preventing BlockHound from launching.
  - The `-XX:+AllowRedefinitionToAddDeleteMethods` option has already been addressed in `build.gradle`.
- The remaining CI errors are on Mac and Windows. These seem to be related to the build environment and are not associated with native compilation.

I'll be checking past issues and PRs that seem to be related to the blueprint for a while.

**Comment by mshima** [comment]
Windows builds are not working because `-Dnative-build-args=-J-Xmx13g` configuration seems to don't be working.

In any case I think we can go ahead and merge. @hide212131 is something missing at this PR?

**Comment by hide212131** [comment]
@mshima Thank you so much for all your help. 

If it's permissible at this point, I would appreciate it if you could merge it. 
Initially, I thought I had to address all the issues listed in the beginning checklist, but I'm starting to feel that adding any more to this PR might be overloading it. 
After it's merged, I'll continue to submit individual PRs for any issues I notice.

**Comment by mshima** [comment]
@hide212131 thanks I think we should split 100 for me and 400 for you.

**Comment by hide212131** [comment]
@mshima Thank you.❤️  In that case, I will proceed accordingly.

**Comment by hide212131** [comment]
bounty claimed https://opencollective.com/generator-jhipster/expenses/178940

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/180757

**Comment by DanielFran** [comment]
@mshima approved

**Pull request merged**
