### PR TITLE
Improve logging

### LINKED ISSUE #10: Tone town logging even more
I tried this in a recent example and found that it logs quite a few messages in the console. I was able to get it down to a reasonable level with the following. It's still more than I'd like, but I'm not sure how to suppress the others.

```yaml
logging:
  level:
    root: ERROR
    io.netty: ERROR
    liquibase: ERROR
    org.hibernate: ERROR
    org.springframework: ERROR
    com.zaxxer.hikari: ERROR
    org.apache.catalina: ERROR
    org.apache.tomcat: ERROR
    tech.jhipster.config: ERROR
    jdk.event.security: ERROR
    java.net: ERROR
    sun.net.www: ERROR
```
Screen Shot 2022-02-16 at 17 58 56

### PR DESCRIPTION
**Pull request by mraible**
Fixes #10.

### CODE REVIEW

**Comment by mshima** [comment]
@mraible do you want to release it or should I?

**Comment by mshima** [comment]
I will do it.

**Comment by mshima** [comment]
Release notes is a draft, so you can add the blog link or any other information.

**Comment by mraible** [comment]
Excellent! We decided to publish my blog post tomorrow. I'll update the release notes when it's live.

**Pull request merged**
